### ISSUE TITLE
A typo 

### ISSUE THREAD

**Issue by SanmerDev** [Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk#1]
https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk/blob/ba0189f5d5f16df8c0c9163e3530ec92accf6fb6/module.prop#L4

This still exists in the latest released [version](https://github.com/Magisk-Modules-Alt-Repo/AdGuardDNS4Magisk/releases/download/2.7f/AdGuardDNS4Magisk-v2.7f.zip).

**Comment by SayaAEP** [comment]
27f mean forked

**Comment by SanmerDev** [comment]
Just add `f` to version, versionCode should be an integer 😋.

Refer to [Magisk Developer Guides](https://topjohnwu.github.io/Magisk/guides.html#moduleprop)
